name: ğŸ—‘ï¸ Remove PR Preview

on:
  push

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  remove:
    name: ğŸ—‘ï¸ Remove PR Preview
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.0.0"

      - name: ğŸ¤ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 900

      - name: Remove PR Preview
        run: |
<<<<<<< HEAD
<<<<<<< HEAD
          pnpm sst remove --stage prod
        env:
          AWS_DOMAIN: ${{ secrets.AWS_DOMAIN }}
          AWS_CERTIFICATE_ARN: ${{ secrets.AWS_CERTIFICATE_ARN }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_REPORT_URL: ${{ secrets.SENTRY_REPORT_URL }}
=======
          bunx sst remove --stage pr${{ github.event.number }}
>>>>>>> 6ad48e7 (chore: migrate to bun)
=======
          bun run sst:remove --stage pr${{ github.event.number }}
>>>>>>> 257c3b9 (ci: update commands)
