name: üóëÔ∏è Remove PR Preview

on:
  push

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  remove:
    name: üóëÔ∏è Remove PR Preview
    runs-on: ubuntu-latest

    steps:
      - name: ‚¨áÔ∏è Checkout repo
        uses: actions/checkout@v3

      - name: ‚éî Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: üüß Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: ü§ù Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 900

      - name: Remove PR Preview
        run: |
          pnpm sst remove --stage prod
        env:
          AWS_DOMAIN: ${{ secrets.AWS_DOMAIN }}
          AWS_CERTIFICATE_ARN: ${{ secrets.AWS_CERTIFICATE_ARN }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_REPORT_URL: ${{ secrets.SENTRY_REPORT_URL }}
